// <auto-generated />
namespace Mvc.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class category_to_prod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(category_to_prod));
        
        string IMigrationMetadata.Id
        {
            get { return "201801232223555_category_to_prod"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
