// <auto-generated />
namespace Mvc.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CompareTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CompareTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201802032137387_CompareTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
